language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
matrix:
  allow_failures:
    - python:
      - "3.2"
      - "3.3"
install: >
  if test -e requirements-dev-$TRAVIS_PYTHON_VERSION.txt; then
    pip install -r requirements-dev-$TRAVIS_PYTHON_VERSION.txt --use-mirrors
  else
    pip install -r requirements-dev.txt --use-mirrors
  fi &&
  sudo apt-get install vsftpd
script: >
  export PYCURL_VSFTPD_PATH=/usr/sbin/vsftpd &&
  make test
