sudo: false
language: python
matrix:
  include:
    # all supported Python versions
    - python: 2.6
      env:
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      # docs are built for most recent libcurl, below
    - python: 2.7
      env:
        - USEPY=3.1
        - TESTDOCSEXAMPLES=1
    - python: 3.2
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.3
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.4
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.5
      # docs are built for most recent libcurl, below

    # minimum libcurl we support
    - python: 2.7
      env:
        - USECURL=7.19.0-gssapi
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1

    # latest libcurl with each supported SSL backend
    - python: 2.7
      env:
        - USECURL=7.52.1-gssapi-libssh2
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USECURL=7.52.1-gssapi-libssh2
        - USESSL=libressl
        - USELIBRESSL=2.2.0
    - python: 2.7
      env:
        # libcurl 7.45.0, 7.46.0 do not build against gnutls
        # in travis/ubuntu 12.04
        # did not test 7.52.1
        - USECURL=7.44.0-gssapi-libssh2
        - USESSL=gnutls
    - python: 2.7
      env:
        - USECURL=7.52.1-gssapi-libssh2
        - USESSL=nss
    - python: 2.7
      env:
        # this configuration should be without gssapi
        - USECURL=7.52.1
        - USESSL=none

    # latest libcurl with each SSL backend that uses different code,
    # see #357/#360
    - python: 3.5
      env:
        - USECURL=7.52.1-gssapi-libssh2
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1
    # no need to test libressl because it's treated exactly like openssl
    - python: 3.5
      env:
        # libcurl 7.45.0, 7.46.0 do not build against gnutls
        # in travis/ubuntu 12.04
        # did not test 7.52.1
        - USECURL=7.44.0-gssapi-libssh2
        - USESSL=gnutls
    - python: 3.5
      env:
        - USECURL=7.52.1-gssapi-libssh2
        - USESSL=nss
    # no need to test ssl-less configuration because there is no code that
    # is specific to it

    # AVOIDSTDIO tested on one Python version, must be Python 2.x
    - python: 2.7
      env:
        - AVOIDSTDIO=yes

    # common distributions:
    # CentOS 6
    - python: 2.6
      env:
        - USECURL=7.19.7-gssapi
        - USESSL=openssl
        - USEOPENSSL=1.0.1e
    # Debian Wheezy
    - python: 2.7
      env:
        - USECURL=7.26.0-gssapi
        - USESSL=gnutls
    # Debian Jessie
    - python: 3.4
      env:
        - USECURL=7.38.0-gssapi
        - USESSL=gnutls
    - python: 3.5
      env:
        - USECURL=7.53.0-dev-gssapi-libssh2
        - USESSL=openssl
    - python: 3.5
      env:
        - USECURL=7.53.0-dev-gssapi-libssh2
        - USESSL=nss
install: >
  ./tests/travis/setup.sh
before_script: >
  ./tests/travis/hack.sh
script: >
  ./tests/travis/run.sh
addons:
  apt:
    packages:
      - libssh2-1
